"""
Django settings for wwustc project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""
import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), 'globalvalues'))

from GlobalSettings import GlobalSettings

globalSettings = GlobalSettings()

# Disgusting looking code below that sets many variables to that of the global config
# Skip to next comment
#-----------------------------------------------------------------------------#
BASE_DIR = globalSettings.BASE_DIR
SECRET_KEY = globalSettings.SECRET_KEY
ALLOWED_HOSTS = globalSettings.ALLOWED_HOSTS
INSTALLED_APPS = globalSettings.INSTALLED_APPS
MIDDLEWARE = globalSettings.MIDDLEWARE
LOGIN_URL = globalSettings.LOGIN_URL
LOGIN_REDIRECT_URL = globalSettings.LOGIN_REDIRECT_URL
AUTHENTICATED_BACKENDS = globalSettings.AUTHENTICATED_BACKENDS
ROOT_URLCONF = globalSettings.ROOT_URLCONF
WSGI_APPLICATION = globalSettings.WSGI_APPLICATION
DATABASES = globalSettings.DATABASES
AUTH_PASSWORD_VALIDATORS = globalSettings.AUTH_PASSWORD_VALIDATORS
LANGUAGE_CODE = globalSettings.LANGUAGE_CODE
TIME_ZONE = globalSettings.TIME_ZONE
USE_I18N = globalSettings.USE_I18N
USE_L10N = globalSettings.USE_L10N
USE_TZ = globalSettings.USE_TZ
STATIC_URL = globalSettings.STATIC_URL
MEDIA_URL = globalSettings.MEDIA_URL
SITE_ID = globalSettings.SITE_ID
WIKI_ACCOUNT_HANDLING = globalSettings.WIKI_ACCOUNT_HANDLING
WIKI_ACCOUNT_SIGNUP_ALLOWED = globalSettings.WIKI_ACCOUNT_SIGNUP_ALLOWED
ADMIN_LIST = globalSettings.ADMIN_LIST
NUM_USERS = globalSettings.NUM_USERS
CREATING_SHIFTS = globalSettings.CREATING_SHIFTS
USER_SHIFT_PLACE = globalSettings.USER_SHIFT_PLACE
MOTD = globalSettings.MOTD
#-----------------------------------------------------------------------------#

# Variables tied to prod
STATIC_ROOT = '/var/www/wwustc/static/'
MEDIA_ROOT = '/var/www/wwustc/media/'
SECURE_SSL_REDIRECT = True
DEBUG = False

#-----------------------------------------------------------------------------#
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'debug': DEBUG,
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'sekizai.context_processors.sekizai',
            ],
        },
    },
]
